

== Integration und Kompatibilität

Wesentlich für den Erfolg eines Test-Frameworks sind nicht nur moderne oder elegante Features,
sondern vor allem auch die Integration in andere Werkzeuge.
Die Ausführung von Tests innerhalb einer IDE wurde oben bereits ausführlich gezeigt,
mindestends ebenso wichtig ist sicherlich die Integration mit CLI-basierten Buildtools,
die in CI-Builds zum Einsatz kommen.

=== Buildtools

Die meisten Projekte im Java-Umfeld werden heute sicherlich mit Maven oder Gradle gebaut.
Daher hat das JUnit 5-Team von Anfang an ein Gradle Plugin
und einen Maven Surefire Provider mitentwickelt.
Der Surefire Provider wurde bereits an das entsprechende Apache-Projekt übergeben,
um dort weiterentwickelt zu werden;
für das Gradle Plugin ist ein ähnliches Vorgehen in Vorbereitung.
Möchte man eine JUnit 5-Projekt mit Maven oder Gradle neu aufsetzen,
so lohnt sich ein Blick auf die entsprechenden Beispielprojekte [8].


Zusätzlich zu dieser Buildtool-Integration gibt es einen `ConsoleLauncher`,
der mit zahlreichen Optionen parametrisierbar ist
und das Ergebnis einer Testausführung in einer wohlformatierten Baumdarstellung ausgibt.
Dazu gibt es im zentralen Maven-Repository unter der Dependency _junit-platform-console-standalone_
ein stand-alone Executable, was direkt mit `java -jar` aufgerufen werden kann.
Mit diesem Werkzeug wäre auch eine Integration in nicht direkt unterstützte Buildtools (z.B. Ant) realisierbar.


=== JUnit 4 und 5 (Jupiter)

Wie bereits im Abschnitt über die Architektur erwähnt,
war es ein wesentliches Designziel,
mehrere Engines in einem einzigen Lauf gleichzeitig ausführen zu können.
Dies gilt natürlich insbesondere für die Koexistenz von JUnit 4- und Junit Jupiter-Tests.
Für die Ausführung von Junit 4-Tests innerhalb einer neuen JUnit 5-Umgebung
existiert die bereits beschriebene JUnit-Vintage-Engine.
Umgekehrt lassen sich neue Jupiter-Tests in JUnit 4-Umgebungen ausführen,
wenn man den entsprechenden Runner
`org.junit.platform.runner.JUnitPlatform`
aus der Dependency
_junit-platform-runner_
verwendet,
der das Jupiter-Programmiermodell bestmöglich auf die in JUnit 4 vorhandenen Abstraktionen übersetzt.
Auch wenn beide Integrationen eher nicht
für eine dauerhafte Verwendung vorgesehen sind,
so lassen sich doch einige Migrationsjahre damit bestreiten.


=== Java 9


Seit Version 5.0.0 kann JUnit 5 zusammen mit Java 9 verwendet werden,
die CI-Builds laufen schon seit einigen Monaten sowohl gegen Java 8 als auch Java 9.
Die Modulinformation wird derzeit noch automatisch generiert,
d.h. dass im Moment noch alle Klassen physisch verwendbar sind.
Um für die Zukunft gewappnet zu sein,
sollte man als Anwender jedoch bereits jetzt auf die Verwendung von Klassen verzichten,
die mit `@API(Status.INTERNAL)` annotiert sind.

