== Hintergrund und Motivation

Das Test-Framework JUnit hat seit dem ersten Release im Jahr 2000 wesentlich dazu beigetragen,
testgetriebene Entwicklung zu ermöglichen.
Der Legende nach wurde es ursprünglich von Kent Beck und Erich Gamma im Flugzeug per Pair-Programming entwickelt [1]
und war seitdem Vorbild für viele andere Test-Frameworks.
Nach einer aktuellen Untersuchung vom Juli diesen Jahres [2] ist JUnit die am meisten verwendete Java-Bibliothek überhaupt.

Nach vielen Jahren der Weiterentwicklung und Wartung war JUnit 4 bei Version 4.12 angelangt.
Im Lauf der Jahre hatte es sich gezeigt,
dass die zur Verfügung stehenden Konstrukte die Komponierbarkeit von Erweiterungen erschwerten.
Auch die Art und Weise, in der IDEs JUnit integrierten,
stellte sich als zunehmend hinderlich für die Weiterentwicklung heraus.
Dazu kommt, dass die vorherigen Versionen naturgemäß keine Sprachfeatures von Java 8 unterstützen konnten,
weil stets die Kompatibilität zu Java 5 gewahrt bleiben musste.

Nach längerer Zeit ohne neue Releases und ohne grundlegende Modernisierungsmöglichkeit
hat im Oktober 2015 die Entwicklung der vollständig überarbeiteten Version 5 begonnen.
Nach einer Startfinanzierung durch die Crowdfunding-Kampagne "JUnit Lambda"
begann im Oktober 2015 die Planung der neuen Version bei einem Workshop mit dem Core-Committer-Team
und Herstellern der Tools Eclipse, Intellij Idea, Gradle und Pivotal (Spring Framework).
Nach einem Prototypen und einer Reihe von Milestone-Releases
ist im Sommer 2017 mit der Version 5.0.0 GA das erste Produktionsrelease der neuen Version erschienen.
Version 5.1 ist bereits in Planung.


Im Folgenden werden wir einen Überblick über
das neue Programmiermodell und das zugehörige API,
die neue Gesamtarchitektur,
sowie die Themen Erweiterbarkeit und Integrierbarkeit geben.

